[colors.primary]
background = '#101010'
foreground = '#c7c7c7'

[colors.normal]
black = '#101010'
red = '#e7514b'
green = '#98971a'
yellow = '#d79921'
blue = '#458588'
magenta = '#b16286'
cyan = '#458588'
white = '#c7c7c7'

# Bright colors
[colors.bright]
black = '#202020'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
magenta = '#d3869b'
cyan = '#83a598'
white = '#ffeeee'
