local normal = require('groov.palette').normal
local bright = require('groov.palette').bright
local lighten = require('groov.palette').lighten

return {
  Comment = { fg = normal.green, italic = true },
  ColorColumn = { bg = bright.bg },
  Conceal = { fg = normal.blue },
  Cursor = { fg = normal.bg, bg = normal.fg },
  lCursor = { fg = normal.bg, bg = normal.fg },
  CursorIM = { fg = normal.bg, bg = normal.fg },
  CursorColumn = { bg = bright.bg },
  CursorLine = { bg = bright.bg },
  Directory = { fg = bright.blue },
  DiffAdd = { bg = normal.green },
  DiffChange = { bg = normal.yellow },
  DiffDelete = { bg = normal.red },
  DiffText = { bg = normal.purple },
  EndOfBuffer = { fg = normal.bg },
  ErrorMsg = { fg = normal.red },
  VertSplit = { fg = bright.blue },
  WinSeparator = { fg = bright.blue, bold = true },
  Folded = { fg = normal.blue, bg = bright.bg },
  FoldColumn = { bg = normal.bg, fg = normal.purple },
  SignColumn = { bg = normal.bg, fg = normal.purple },
  SignColumnSB = { bg = normal.bg, fg = normal.fg },
  Substitute = { bg = normal.red, fg = normal.bg },
  LineNr = { fg = bright.bg },
  LineNrAbove = { fg = bright.bg },
  LineNrBelow = { fg = bright.bg },
  MatchParen = { fg = bright.purple, bold = true },
  ModeMsg = { fg = normal.fg, bold = true },
  MsgArea = { fg = bright.fg },
  MoreMsg = { fg = normal.blue },
  NonText = { fg = bright.bg },
  Normal = { fg = normal.fg, bg = normal.bg },
  NormalNC = { fg = normal.fg, bg = normal.bg },
  NormalSB = { fg = normal.fg, bg = normal.bg },
  NormalFloat = { fg = normal.fg, bg = bright.bg },
  FloatBorder = { fg = bright.bg, bg = bright.bg },
  FloatTitle = { fg = bright.purple, bg = normal.bg },
  Pmenu = { bg = bright.bg, fg = normal.fg },
  PmenuSel = { bg = lighten(normal.bg, 1.1) },
  PmenuSbar = { bg = lighten(normal.bg, 1.2) },
  PmenuThumb = { bg = lighten(normal.bg, 1.3) },
  Question = { fg = normal.blue },
  QuickFixLine = { bg = bright.bg, bold = true },
  Search = { bg = normal.purple },
  IncSearch = { bg = normal.purple },
  CurSearch = { link = 'IncSearch' },
  SpecialKey = { fg = normal.fg },
  SpellBad = { sp = normal.red, undercurl = true },
  SpellCap = { sp = normal.yellow, undercurl = true },
  SpellLocal = { sp = normal.green, undercurl = true },
  SpellRare = { sp = normal.blue, undercurl = true },
  StatusLine = { fg = normal.fg, bg = lighten(normal.bg, 0.9) },
  StatusLineNC = { fg = normal.fg, bg = lighten(normal.bg, 0.9) },
  TabLine = { bg = lighten(normal.bg, 0.9), fg = normal.blue },
  TabLineFill = { bg = lighten(normal.bg, 0.8) },
  TabLineSel = { fg = normal.bg, bg = bright.blue },
  Title = { fg = normal.red, bold = true },
  Visual = { bg = bright.blue },
  VisualNOS = { bg = normal.blue },
  WarningMsg = { fg = normal.yellow },
  Whitespace = { fg = bright.bg },
  WildMenu = { bg = normal.blue },
  WinBar = { link = 'StatusLine' },
  WinBarNC = { link = 'StatusLineNC' },

  Bold = { bold = true, fg = normal.fg },
  Character = { fg = bright.green },
  Constant = { fg = normal.yellow },
  Debug = { fg = normal.yellow },
  Delimiter = { link = 'Special' },
  Error = { fg = bright.red },
  Function = { fg = bright.fg },
  Identifier = { fg = normal.purple },
  Italic = { italic = true, fg = normal.fg },
  Keyword = { fg = normal.red },
  Operator = { fg = normal.yellow },
  PreProc = { fg = normal.purple },
  Special = { fg = bright.blue },
  Statement = { fg = normal.red },
  String = { fg = normal.green },
  Todo = { bg = bright.yellow, fg = bright.bg },
  Type = { fg = normal.purple },
  Underlined = { underline = true },
  debugBreakpoint = { bg = bright.green, fg = normal.bg },
  dosIniLabel = { link = '@property' },
  helpCommand = { bg = lighten(normal.bg, 0.7), fg = bright.blue },

  LspReferenceText = { bg = bright.bg },
  LspReferenceRead = { bg = bright.bg },
  LspReferenceWrite = { bg = bright.bg },
  LspCodeLens = { fg = normal.green },
  LspInlayHint = { fg = lighten(bright.bg, 1.5) },
  LspInfoBorder = { fg = bright.bg, bg = bright.bg },

  DiagnosticError = { fg = normal.red, undercurl = true },
  DiagnosticWarn = { fg = normal.yellow },
  DiagnosticInfo = { fg = bright.green },
  DiagnosticHint = { fg = normal.green },
  DiagnosticUnnecessary = { fg = normal.green },

  healthError = { fg = normal.red },
  healthSuccess = { fg = normal.green },
  healthWarning = { fg = normal.yellow },
}
